---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/debian    stretch    stable"
    state: present
    update_cache: true

- name: Install Docker.
  package:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: Add the user 
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes